#!/bin/sh

# script/alpine_setup: Adds all the system packages, directors, users, etc.
#                      required to run the application on Alpine

source "$(dirname "${0}")"/../script/include/global_header.inc.sh

# Set app specific items
APP_USER="crlupdater"
APP_UID="8015"

# Add additional packages required by app dependencies
ADDITIONAL_PACKAGES="bzip2 python3 tar"

# Run the shared alpine setup script
source ./script/include/run_alpine_setup
