#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

source "$(dirname "${0}")"/../script/include/global_header.inc.sh

# Use pip version 19.x
PIP_VERSION='19.*'

# Run the shared setup script
source ./script/include/run_setup
